### ISSUE TITLE
ScalarGaussian not found when running example

### ISSUE THREAD

**Issue by oliparson** [mattjj/pyhsmm-factorial#2]
Hi,

I tried importing example.py and got the following error:

> > > import pyhsmm.plugins.factorial.example
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pyhsmm\plugins\factorial\example.py", line 51, in <module>
> > >     for od,durhypparams in zip([true_obsdistns_chain1,true_obsdistns_chain2],dur
> > > hypparamss)])
> > >   File "pyhsmm\plugins\factorial\models.py", line 92, in **init**
> > >     assert isinstance(distn,pyhsmm.basic.distributions.ScalarGaussian),\
> > > AttributeError: 'module' object has no attribute 'ScalarGaussian'

When I checked the pyhsmm.basic.distributions module, it really does not seem to contain a ScalarGaussian attribute. Has this error been introduced during refactoring or am I doing something wrong?

Thanks,
Oli

**Comment by mattjj** [comment]
I changed some names around recently and didn't update that one. I just pushed a fix in ed5831f.

**Comment by mattjj** [comment]
Actually that had its own import problems, so I changed all the names back to ScalarGaussian. The fix on this repo is 81f4263, but you'll need to update pyhsmm and its pybasicbayes submodle, too. I think running these two commands in the pyhsmm root should do it:

``` bash
git pull origin master
git submodule update --recursive
```

example.py runs for me now; let me know if it gives you trouble!

**Comment by oliparson** [comment]
Thanks for your quick fix. I've pulled your fixes but am still getting trouble:

> > > import pyhsmm.plugins.factorial.example
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pyhsmm/**init**.py", line 2, in <module>
> > >     import models
> > >   File "pyhsmm/models.py", line 7, in <module>
> > >     from basic.abstractions import ModelGibbsSampling, ModelEM
> > >   File "pyhsmm/basic/abstractions.py", line 6, in <module>
> > >     from pybasicbayes.abstractions import *
> > >   File "pyhsmm/basic/pybasicbayes/**init**.py", line 1, in <module>
> > >     import abstractions, distributions, models, util
> > >   File "pyhsmm/basic/pybasicbayes/abstractions.py", line 4, in <module>
> > >     from util.stats import combinedata
> > >   File "pyhsmm/basic/pybasicbayes/util/**init**.py", line 2, in <module>
> > >     import general, plot, stats, text
> > >   File "pyhsmm/basic/pybasicbayes/util/general.py", line 7, in <module>
> > >     potrs, potrf, trtrs = scipy.linalg.lapack.get_lapack_funcs(('potrs','potrf',
> > > 'trtrs'),arrays=False) # arrays=false means type=d
> > >   File "/usr/lib/python2.6/dist-packages/scipy/linalg/lapack.py", line 92, in ge
> > > t_lapack_funcs
> > >     func = getattr(m2,func_name)
> > > AttributeError: 'module' object has no attribute 'dtrtrs'

Any ideas?

**Comment by mattjj** [comment]
It looks like scipy can't grab its wrapped  LAPACK functions, which I call directly just to squeeze out some efficiency in an edge case that was important at one point.

What version of scipy are you using? Is it linked against LAPACK? (There's a way to check the configuration but I can't remember it offhand.)

To avoid those calls we could rewrite the solvers to call np.linalg.solve or scipy.linalg.solve_triangular, but if the issue is an old scipy or one built workout LAPACK bindings, it may be better to fix those issues directly.

**Comment by mattjj** [comment]
Try running these commands:

``` python
scipy.version.version
import numpy.distutils.system_info as sysinfo
sysinfo.get_info('lapack')
```

from http://stackoverflow.com/questions/9000164/how-to-check-blas-lapack-linkage-in-numpy-scipy

My OS X setup with Python from MacPorts and numpy/scipy from the corresponding pip show a scipy version 0.11.0 (I should upgrade that...) and a LAPACK setup of

``` python
{'language': 'f77', 'libraries': ['lapack'], 'library_dirs': ['/usr/lib']}
```

I don't know whether it's possible to have a numpy built with lapack and a scipy built without it, but that seems pretty improbable.

**Comment by oliparson** [comment]
Thanks again for your help, here's the output of those commands:

> > > scipy.version.version
> > > '0.7.0'
> > > import numpy.distutils.system_info as sysinfo
> > > sysinfo.get_info('lapack')
> > > {}

It seems I'm running a much older version of scipy build without LAPACK.

**Comment by mattjj** [comment]
Hm that seems to be the case. If it's feasible to upgrade, that's your best bet! If not, I'm afraid I don't know what edits might retrofit things appropriately.

No problem; thanks for trying out the code!
